version: "3.3"

services:
  jigsaw_build:
    command: ["jigsaw", "build"]
    image: "eagledata/jigsaw-docker"
    volumes:
      - ./:/app

  jigsaw_dev:
    command: ["npm", "run", "watch"]
    depends_on:
      - jigsaw_build
    environment:
      - NODE_ENV=development
    image: "eagledata/jigsaw-docker"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
